language: generic 

sudo : required

services:
  - docker

before_install:
  - docker build -t pb2323/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true pb2323/docker-react npm run test 