language: generic 

sudo : required
services:
  - docker

before_install:
  - docker build -t pb2323/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true pb2323/docker-react npm run test 

deploy:
  provider: "elasticbeanstalk"
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-324131767317"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
